### ISSUE TITLE
Failing using str-replace

### ISSUE THREAD

**Issue by LeoSeyers** [shitiomatic/str-replace#1]
Hello,

I'm new to the Git Actions world and I'm failing to use your action for some reasons.
I have no error messages.

I'd like to replace a string in my functions.php to invalidate cached assets (for my Wordpress CI). 
Utimately I'd like to replace this string with ${GITHUB_SHA} .

Any help would be appreciated, thank you!

```yaml
on: push
name: Push Routine
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
        
    - name: Replacing hash (Action) # this does not produce any results
      uses: shitiomatic/str-replace@master
      with:
        find: "{#COMMIT-HASH#}"
        replace: "test"
        include: "functions.php"

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build Project
      run: |
        npm install
        npm run production
        
    - name: Replacing hash (Node) # uses 'replace-in-file' package, works locally but fails with my action with an unhandled promise rejection
      run: 
        npm run hash
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: app
        git-ftp-args: --insecure
```

**Comment by shitiomatic** [comment]
```yaml
- name: Replacing hash (Action)
    uses: shitiomatic/str-replace@master
    with:
      find: "{#COMMIT-HASH#}"
      replace: "${{ github.sha }}"
      include: "functions.php"
```
